# Generated by Django 2.2.8 on 2020-08-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_auto_20200807_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='avatar',
            field=models.ImageField(upload_to=''),
        ),
    ]
