# Generated by Django 2.2.8 on 2020-08-07 05:56

from django.db import migrations, models
import taskapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_auto_20200807_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='avatar',
            field=models.ImageField(upload_to=taskapp.models.project_image_store),
        ),
    ]
