# Generated by Django 2.2.8 on 2020-08-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_auto_20200807_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
