# Generated by Django 2.2.8 on 2020-08-09 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0006_auto_20200809_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_by_project', to='taskapp.Projects'),
        ),
    ]
